'use client';

import { useEffect, useState } from 'react';
import { Button, Card, Descriptions, Form, Input, Modal, Select, Space, Table, Tabs, Tag } from 'antd';

const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';
type Profile = { id: string; titleName: string; taxpayerCode?: string; defaultInvoiceContent?: string; enabled: boolean };
type Task = { id: string; taskNo: string; publicAmount: string; invoiceAmount: string; status: string; payerName?: string; payerAccount?: string; titleName?: string; invoiceContent?: string; remark?: string; customer?: { id: string; name: string; customerCode: string }; creator?: { displayName: string }; reviewer?: { displayName: string }; completedAt?: string; rejectReason?: string; invoiceDetails?: { invoiceCode?: string; amount: string; invoiceType: string }[] };
const labels: Record<string, string> = { PENDING: '待开票', REVIEWING: '审核中', APPROVED: '待完成开票', REJECTED: '审核不通过', COMPLETED: '已完成' };

async function request<T>(path: string, token: string, options?: RequestInit): Promise<T> { const response = await fetch(`${apiUrl}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(options?.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(Array.isArray(data.message) ? data.message.join('；') : data.message || '请求失败'); return data; }

export default function PublicInvoiceTaskPanel({ token, review, onError }: { token: string; review?: boolean; onError: (message: string) => void }) {
  const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(false); const [tab, setTab] = useState('ALL'); const [selected, setSelected] = useState<Task | null>(null); const [profiles, setProfiles] = useState<Profile[]>([]); const [editOpen, setEditOpen] = useState(false); const [completeOpen, setCompleteOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const [form] = Form.useForm(); const [completeForm] = Form.useForm(); const [profileForm] = Form.useForm();
  async function refresh() { setLoading(true); try { const status = tab === 'ALL' ? '' : `&status=${tab}`; const result = await request<{ items: Task[] }>(`/invoice-tasks?page=1&pageSize=100${status}`, token); setTasks(result.items); } catch (error) { onError(error instanceof Error ? error.message : '开票任务查询失败'); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [token, tab]);
  async function openEdit(task: Task) { setSelected(task); try { const rows = await request<Profile[]>(`/customers/${task.customer!.id}/invoice-profiles`, token); setProfiles(rows.filter((item) => item.enabled)); form.setFieldsValue({ invoiceAmount: task.invoiceAmount, titleName: task.titleName, invoiceContent: task.invoiceContent, remark: task.remark }); setEditOpen(true); } catch (error) { onError(error instanceof Error ? error.message : '开票信息读取失败'); } }
  async function updateTask(values: Record<string, string>) { if (!selected) return; try { await request(`/invoice-tasks/${selected.id}`, token, { method: 'PATCH', body: JSON.stringify(values) }); setEditOpen(false); await refresh(); } catch (error) { onError(error instanceof Error ? error.message : '开票任务保存失败'); } }
  async function action(task: Task, name: 'submit' | 'approve' | 'revoke') { try { await request(`/invoice-tasks/${task.id}/${name}`, token, { method: 'POST', body: JSON.stringify({}) }); await refresh(); } catch (error) { onError(error instanceof Error ? error.message : '操作失败'); } }
  async function reject(task: Task) { const reason = window.prompt('请输入驳回原因'); if (!reason) return; try { await request(`/invoice-tasks/${task.id}/reject`, token, { method: 'POST', body: JSON.stringify({ rejectReason: reason }) }); await refresh(); } catch (error) { onError(error instanceof Error ? error.message : '驳回失败'); } }
  async function complete(values: Record<string, string>) { if (!selected) return; try { await request(`/invoice-tasks/${selected.id}/complete`, token, { method: 'POST', body: JSON.stringify(values) }); setCompleteOpen(false); await refresh(); } catch (error) { onError(error instanceof Error ? error.message : '完成开票失败'); } }
  async function createProfile(values: Record<string, string>) { if (!selected) return; try { await request(`/customers/${selected.customer!.id}/invoice-profiles`, token, { method: 'POST', body: JSON.stringify(values) }); setProfileOpen(false); await openEdit(selected); } catch (error) { onError(error instanceof Error ? error.message : '开票信息保存失败'); } }
  return <Card title={review ? '发票审核' : '发票申请'} loading={loading}>
    <Tabs activeKey={tab} onChange={setTab} items={[{ key: 'ALL', label: '全部' }, ...Object.entries(labels).map(([key, label]) => ({ key, label }))]} />
    <Table rowKey="id" dataSource={tasks} pagination={{ pageSize: 20 }} columns={[
      { title: '任务编号', dataIndex: 'taskNo' }, { title: '客户', render: (_: unknown, row: Task) => row.customer?.name || '-' }, { title: '付款账户', render: (_: unknown, row: Task) => row.payerAccount || row.payerName || '-' }, { title: '对公入账金额', dataIndex: 'publicAmount' }, { title: '需开票金额', dataIndex: 'invoiceAmount' }, { title: '开票信息', dataIndex: 'titleName', render: (value: string) => value || '-' }, { title: '状态', dataIndex: 'status', render: (value: string) => <Tag>{labels[value] || value}</Tag> }, { title: '审核人', render: (_: unknown, row: Task) => row.reviewer?.displayName || '-' }, { title: '完成时间', dataIndex: 'completedAt', render: (value?: string) => value ? new Date(value).toLocaleString('zh-CN') : '-' },
      { title: '操作', render: (_: unknown, row: Task) => <Space><Button type="link" onClick={() => void openEdit(row)} disabled={row.status === 'COMPLETED'}>{['PENDING', 'REJECTED'].includes(row.status) ? '编辑' : '查看'}</Button>{!review && ['PENDING', 'REJECTED'].includes(row.status) && <Button type="link" onClick={() => void action(row, 'submit')}>提交审核</Button>}{row.status === 'REVIEWING' && <Button type="link" onClick={() => void action(row, 'revoke')}>撤回</Button>}{review && row.status === 'REVIEWING' && <><Button type="link" onClick={() => void action(row, 'approve')}>审核通过</Button><Button type="link" danger onClick={() => void reject(row)}>驳回</Button></>}{row.status === 'APPROVED' && <Button type="link" onClick={() => { setSelected(row); completeForm.setFieldsValue({ amount: row.invoiceAmount, invoiceContent: row.invoiceContent }); setCompleteOpen(true); }}>完成开票</Button>}{row.status === 'COMPLETED' && <Button type="link" onClick={() => void openEdit(row)}>查看发票</Button>}</Space> },
    ]} />
    <Modal title="编辑开票任务" open={editOpen} onCancel={() => setEditOpen(false)} onOk={() => form.submit()} okText="保存" cancelText="取消"><Form form={form} layout="vertical" onFinish={updateTask}><Descriptions size="small" bordered column={1}><Descriptions.Item label="客户">{selected?.customer?.name}</Descriptions.Item><Descriptions.Item label="付款账户">{selected?.payerAccount || selected?.payerName || '-'}</Descriptions.Item><Descriptions.Item label="对公入账金额">{selected?.publicAmount}</Descriptions.Item></Descriptions><Form.Item name="invoiceAmount" label="需开票金额" rules={[{ required: true, message: '请输入需开票金额' }]}><Input disabled={selected?.status === 'COMPLETED'} /></Form.Item><Form.Item name="invoiceProfileId" label="客户开票信息"><Select allowClear disabled={selected?.status === 'COMPLETED'} onChange={(profileId) => { const profile = profiles.find((item) => item.id === profileId); if (profile) form.setFieldsValue({ titleName: profile.titleName, invoiceContent: profile.defaultInvoiceContent }); }} options={profiles.map((item) => ({ value: item.id, label: `${item.titleName}${item.taxpayerCode ? `（${item.taxpayerCode}）` : ''}` }))} /></Form.Item><Button type="link" onClick={() => setProfileOpen(true)}>新增客户开票信息</Button><Form.Item name="titleName" label="发票抬头"><Input disabled={selected?.status === 'COMPLETED'} /></Form.Item><Form.Item name="invoiceContent" label="开票内容"><Input disabled={selected?.status === 'COMPLETED'} /></Form.Item><Form.Item name="remark" label="备注"><Input disabled={selected?.status === 'COMPLETED'} /></Form.Item></Form></Modal>
    <Modal title="完成开票" open={completeOpen} onCancel={() => setCompleteOpen(false)} onOk={() => completeForm.submit()} okText="完成开票" cancelText="取消"><Form form={completeForm} layout="vertical" onFinish={complete}><Form.Item name="invoiceCode" label="发票号码"><Input /></Form.Item><Form.Item name="amount" label="实际开票金额" rules={[{ required: true, message: '请输入实际开票金额' }]}><Input /></Form.Item><Form.Item name="invoiceDate" label="开票日期"><Input placeholder="2026-09-13" /></Form.Item><Form.Item name="invoiceType" label="发票类型" rules={[{ required: true, message: '请选择发票类型!' }]}><Select options={['增值税电子专用发票', '增值税电子普通发票', '增值税专用发票', '增值税普通发票', '形式发票'].map((item) => ({ value: item, label: item }))} /></Form.Item><Form.Item name="invoiceContent" label="开票内容"><Input /></Form.Item><Form.Item name="remark" label="备注"><Input /></Form.Item><Form.Item name="invoiceUrl" label="附件地址（可选）"><Input /></Form.Item></Form></Modal>
    <Modal title="新增客户开票信息" open={profileOpen} onCancel={() => setProfileOpen(false)} onOk={() => profileForm.submit()} okText="保存" cancelText="取消"><Form form={profileForm} layout="vertical" onFinish={createProfile}><Form.Item name="titleName" label="发票抬头" rules={[{ required: true, message: '请输入发票抬头' }]}><Input /></Form.Item><Form.Item name="taxpayerCode" label="纳税人识别号"><Input /></Form.Item><Form.Item name="address" label="地址"><Input /></Form.Item><Form.Item name="phone" label="电话"><Input /></Form.Item><Form.Item name="bankName" label="开户行"><Input /></Form.Item><Form.Item name="bankAccount" label="银行账号"><Input /></Form.Item><Form.Item name="defaultInvoiceContent" label="默认开票内容"><Input /></Form.Item></Form></Modal>
  </Card>;
}
