'use client';

import { useEffect, useMemo, useState } from 'react';
import { Button, Card, Descriptions, Form, Input, Modal, Select, Space, Table, Tabs, Tag } from 'antd';

const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';
type Profile = { id: string; titleName: string; taxpayerCode?: string; defaultInvoiceContent?: string; enabled: boolean; isDefault?: boolean };
type Task = { id: string; taskNo: string; publicAmount: string; invoiceAmount: string; status: string; payerName?: string; payerAccount?: string; titleName?: string; taxpayerCode?: string; address?: string; phone?: string; bankName?: string; bankAccount?: string; invoiceContent?: string; remark?: string; submittedAt?: string; reviewedAt?: string; completedAt?: string; rejectReason?: string; approvalRemark?: string; customer?: { id: string; name: string; customerCode: string }; receiveRecordDetail?: { receiveRecord?: { receivedAt?: string } }; creator?: { id: string; displayName: string }; reviewer?: { displayName: string }; completer?: { displayName: string }; invoiceDetails?: { invoiceCode?: string; amount: string; invoiceType: string; invoiceDate?: string; invoiceContent?: string }[]; auditLogs?: { actionType: string; createdAt: string }[] };
type Mode = 'manage' | 'review' | 'complete';
const labels: Record<string, string> = { PENDING: '待开票', REVIEWING: '审核中', APPROVED: '待完成开票', REJECTED: '已驳回', COMPLETED: '已完成' };
const colors: Record<string, string> = { PENDING: 'default', REVIEWING: 'processing', APPROVED: 'gold', REJECTED: 'red', COMPLETED: 'green' };

async function request<T>(path: string, token: string, options?: RequestInit): Promise<T> {
  const response = await fetch(`${apiUrl}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(options?.headers || {}) } });
  const data = await response.json();
  if (!response.ok) throw new Error(Array.isArray(data.message) ? data.message.join('；') : data.message || '请求失败');
  return data;
}

export default function PublicInvoiceTaskPanel({ token, mode = 'manage', onError }: { token: string; mode?: Mode; onError: (message: string) => void }) {
  const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(false); const [tab, setTab] = useState('ALL'); const [keyword, setKeyword] = useState(''); const [selected, setSelected] = useState<Task | null>(null); const [profiles, setProfiles] = useState<Profile[]>([]); const [detailOpen, setDetailOpen] = useState(false); const [editOpen, setEditOpen] = useState(false); const [completeOpen, setCompleteOpen] = useState(false); const [rejectOpen, setRejectOpen] = useState(false);
  const [form] = Form.useForm(); const [completeForm] = Form.useForm(); const [rejectForm] = Form.useForm();
  const title = mode === 'review' ? '财务审核' : mode === 'complete' ? '完成开票' : '发票任务管理';
  const allowedTabs = useMemo(() => mode === 'review' ? ['ALL', 'REVIEWING', 'APPROVED', 'REJECTED'] : mode === 'complete' ? ['ALL', 'APPROVED', 'COMPLETED'] : ['ALL', 'PENDING', 'REVIEWING', 'APPROVED', 'COMPLETED', 'REJECTED'], [mode]);

  async function refresh(nextKeyword = keyword) { setLoading(true); try { const query = new URLSearchParams({ page: '1', pageSize: '100' }); if (tab !== 'ALL') query.set('status', tab); if (nextKeyword.trim()) query.set('keyword', nextKeyword.trim()); const result = await request<{ items: Task[] }>(`/invoice-tasks?${query.toString()}`, token); setTasks(result.items); } catch (error) { onError(error instanceof Error ? error.message : '开票任务查询失败'); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, [token, tab, mode]);
  async function showDetail(task: Task) { try { const result = await request<Task>(`/invoice-tasks/${task.id}`, token); setSelected(result); setDetailOpen(true); } catch (error) { onError(error instanceof Error ? error.message : '开票任务详情读取失败'); } }
  async function openEdit(task: Task) { setSelected(task); try { const rows = await request<Profile[]>(`/customers/${task.customer!.id}/invoice-profiles`, token); setProfiles(rows.filter((item) => item.enabled)); form.setFieldsValue({ invoiceAmount: task.invoiceAmount, invoiceProfileId: undefined, titleName: task.titleName, taxpayerCode: task.taxpayerCode, address: task.address, phone: task.phone, bankName: task.bankName, bankAccount: task.bankAccount, invoiceContent: task.invoiceContent, remark: task.remark }); setEditOpen(true); } catch (error) { onError(error instanceof Error ? error.message : '开票信息读取失败'); } }
  async function updateTask(values: Record<string, string>) { if (!selected) return; try { await request(`/invoice-tasks/${selected.id}`, token, { method: 'PATCH', body: JSON.stringify(values) }); setEditOpen(false); await refresh(); } catch (error) { onError(error instanceof Error ? error.message : '开票任务保存失败'); } }
  async function action(task: Task, name: 'submit' | 'approve' | 'revoke') { try { await request(`/invoice-tasks/${task.id}/${name}`, token, { method: 'POST', body: JSON.stringify({}) }); await refresh(); } catch (error) { onError(error instanceof Error ? error.message : '操作失败'); } }
  async function reject(values: { rejectReason: string }) { if (!selected) return; try { await request(`/invoice-tasks/${selected.id}/reject`, token, { method: 'POST', body: JSON.stringify(values) }); setRejectOpen(false); rejectForm.resetFields(); await refresh(); } catch (error) { onError(error instanceof Error ? error.message : '驳回失败'); } }
  async function complete(values: Record<string, string>) { if (!selected) return; try { await request(`/invoice-tasks/${selected.id}/complete`, token, { method: 'POST', body: JSON.stringify(values) }); setCompleteOpen(false); completeForm.resetFields(); await refresh(); } catch (error) { onError(error instanceof Error ? error.message : '完成开票失败'); } }
  function selectProfile(profileId: string) { const profile = profiles.find((item) => item.id === profileId); if (!profile) return; form.setFieldsValue({ titleName: profile.titleName, taxpayerCode: profile.taxpayerCode, invoiceContent: profile.defaultInvoiceContent }); }

  return <Card title={title} loading={loading} extra={<Space><Input value={keyword} placeholder="任务编号/付款账户" allowClear onChange={(event) => setKeyword(event.target.value)} onPressEnter={() => void refresh()} style={{ width: 220 }} /><Button onClick={() => void refresh()}>查询</Button></Space>}>
    <Tabs activeKey={tab} onChange={setTab} items={allowedTabs.map((key) => ({ key, label: key === 'ALL' ? '全部' : labels[key] }))} />
    <Table rowKey="id" dataSource={tasks} pagination={{ pageSize: 20 }} scroll={{ x: 1350 }} columns={[
      { title: '任务编号', dataIndex: 'taskNo', width: 190 }, { title: '客户名称', render: (_: unknown, row: Task) => row.customer?.name || '-' }, { title: '付款账户', render: (_: unknown, row: Task) => row.payerAccount || row.payerName || '-' }, { title: '付款时间', render: (_: unknown, row: Task) => row.receiveRecordDetail?.receiveRecord?.receivedAt ? new Date(row.receiveRecordDetail.receiveRecord.receivedAt).toLocaleString('zh-CN') : '-' }, { title: '对公金额', dataIndex: 'publicAmount' }, { title: '状态', dataIndex: 'status', render: (value: string) => <Tag color={colors[value]}>{labels[value] || value}</Tag> }, { title: '创建人', render: (_: unknown, row: Task) => row.creator?.displayName || '-' }, { title: '审核人', render: (_: unknown, row: Task) => row.reviewer?.displayName || '-' },
      { title: '操作', fixed: 'right', render: (_: unknown, row: Task) => <Space size={0}><Button type="link" onClick={() => void showDetail(row)}>查看</Button>{mode === 'manage' && ['PENDING', 'REJECTED'].includes(row.status) && <><Button type="link" onClick={() => void openEdit(row)}>编辑</Button><Button type="link" onClick={() => void action(row, 'submit')}>提交审核</Button></>}{mode === 'manage' && row.status === 'REVIEWING' && <Button type="link" onClick={() => void action(row, 'revoke')}>撤回</Button>}{mode === 'review' && row.status === 'REVIEWING' && <><Button type="link" onClick={() => void action(row, 'approve')}>通过</Button><Button type="link" danger onClick={() => { setSelected(row); setRejectOpen(true); }}>驳回</Button></>}{mode === 'complete' && row.status === 'APPROVED' && <Button type="link" onClick={() => { setSelected(row); completeForm.setFieldsValue({ amount: row.invoiceAmount, invoiceContent: row.invoiceContent }); setCompleteOpen(true); }}>完成开票</Button>}</Space> },
    ]} />
    <Modal title="编辑开票任务" open={editOpen} onCancel={() => setEditOpen(false)} onOk={() => form.submit()} okText="保存" cancelText="取消" width={680}><Form form={form} layout="vertical" onFinish={updateTask}><Descriptions size="small" bordered column={2}><Descriptions.Item label="客户">{selected?.customer?.name}</Descriptions.Item><Descriptions.Item label="付款账户">{selected?.payerAccount || selected?.payerName || '-'}</Descriptions.Item><Descriptions.Item label="对公入账金额">{selected?.publicAmount}</Descriptions.Item><Descriptions.Item label="任务编号">{selected?.taskNo}</Descriptions.Item></Descriptions><Form.Item name="invoiceAmount" label="需开票金额" rules={[{ required: true, message: '请输入需开票金额' }]}><Input /></Form.Item><Form.Item name="invoiceProfileId" label="客户开票信息"><Select allowClear placeholder="选择后保存快照" onChange={selectProfile} options={profiles.map((item) => ({ value: item.id, label: `${item.isDefault ? '【默认】' : ''}${item.titleName}${item.taxpayerCode ? `（${item.taxpayerCode}）` : ''}` }))} /></Form.Item><Form.Item name="titleName" label="公司名称"><Input /></Form.Item><Form.Item name="taxpayerCode" label="纳税人识别号"><Input /></Form.Item><Form.Item name="address" label="地址"><Input /></Form.Item><Form.Item name="phone" label="电话"><Input /></Form.Item><Form.Item name="bankName" label="开户银行"><Input /></Form.Item><Form.Item name="bankAccount" label="银行账号"><Input /></Form.Item><Form.Item name="invoiceContent" label="开票内容"><Input /></Form.Item><Form.Item name="remark" label="备注"><Input.TextArea maxLength={255} showCount /></Form.Item></Form></Modal>
    <Modal title="财务驳回" open={rejectOpen} onCancel={() => setRejectOpen(false)} onOk={() => rejectForm.submit()} okText="确认驳回" cancelText="取消"><Form form={rejectForm} layout="vertical" onFinish={reject}><Form.Item name="rejectReason" label="驳回原因" rules={[{ required: true, message: '请填写驳回原因' }]}><Input.TextArea maxLength={255} showCount /></Form.Item></Form></Modal>
    <Modal title="完成开票" open={completeOpen} onCancel={() => setCompleteOpen(false)} onOk={() => completeForm.submit()} okText="完成开票" cancelText="取消"><Form form={completeForm} layout="vertical" onFinish={complete}><Form.Item name="invoiceCode" label="发票号码"><Input /></Form.Item><Form.Item name="amount" label="实际开票金额" rules={[{ required: true, message: '请输入实际开票金额' }]}><Input /></Form.Item><Form.Item name="invoiceDate" label="开票日期"><Input placeholder="YYYY-MM-DD" /></Form.Item><Form.Item name="invoiceType" label="发票类型" rules={[{ required: true, message: '请选择发票类型!' }]}><Select options={['增值税电子专用发票', '增值税电子普通发票', '增值税专用发票', '增值税普通发票', '形式发票'].map((item) => ({ value: item, label: item }))} /></Form.Item><Form.Item name="invoiceContent" label="开票内容"><Input /></Form.Item><Form.Item name="invoiceUrl" label="附件地址（可选）"><Input /></Form.Item><Form.Item name="remark" label="备注"><Input.TextArea maxLength={255} showCount /></Form.Item></Form></Modal>
    <Modal title="开票任务详情" open={detailOpen} onCancel={() => setDetailOpen(false)} footer={null} width={760}>{selected && <Descriptions bordered column={2}><Descriptions.Item label="任务编号">{selected.taskNo}</Descriptions.Item><Descriptions.Item label="状态"><Tag color={colors[selected.status]}>{labels[selected.status]}</Tag></Descriptions.Item><Descriptions.Item label="客户">{selected.customer?.name || '-'}</Descriptions.Item><Descriptions.Item label="对公金额">{selected.publicAmount}</Descriptions.Item><Descriptions.Item label="付款账户">{selected.payerAccount || selected.payerName || '-'}</Descriptions.Item><Descriptions.Item label="需开票金额">{selected.invoiceAmount}</Descriptions.Item><Descriptions.Item label="公司名称">{selected.titleName || '-'}</Descriptions.Item><Descriptions.Item label="纳税人识别号">{selected.taxpayerCode || '-'}</Descriptions.Item><Descriptions.Item label="地址 / 电话" span={2}>{[selected.address, selected.phone].filter(Boolean).join(' / ') || '-'}</Descriptions.Item><Descriptions.Item label="开户银行 / 账号" span={2}>{[selected.bankName, selected.bankAccount].filter(Boolean).join(' / ') || '-'}</Descriptions.Item><Descriptions.Item label="开票内容" span={2}>{selected.invoiceContent || '-'}</Descriptions.Item><Descriptions.Item label="审核意见" span={2}>{selected.approvalRemark || selected.rejectReason || '-'}</Descriptions.Item><Descriptions.Item label="发票明细" span={2}>{selected.invoiceDetails?.length ? selected.invoiceDetails.map((item) => `${item.invoiceType} ${item.amount} ${item.invoiceCode || ''}`).join('；') : '-'}</Descriptions.Item><Descriptions.Item label="流程记录" span={2}>{selected.auditLogs?.map((item) => `${item.actionType}（${new Date(item.createdAt).toLocaleString('zh-CN')}）`).join(' → ') || '-'}</Descriptions.Item></Descriptions>}</Modal>
  </Card>;
}
